<?php

/**
 * This is the model base class for the table "tbl_user_activity".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserActivity".
 *
 * Columns in table "tbl_user_activity" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $fb_info
 * @property string $activity
 *
 */
abstract class BaseUserActivity extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_user_activity';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserActivity|UserActivities', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('fb_info, activity', 'required'),
			array('fb_info, activity', 'length', 'max'=>20),
			array('id, fb_info, activity', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'fb_info' => Yii::t('app', 'Fb Info'),
			'activity' => Yii::t('app', 'Activity'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('fb_info', $this->fb_info, true);
		$criteria->compare('activity', $this->activity, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}