<?php

/**
 * This is the model base class for the table "tbl_work".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Work".
 *
 * Columns in table "tbl_work" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $employer
 * @property string $location
 * @property string $position
 * @property string $start_date
 * @property string $end_date
 *
 */
abstract class BaseWork extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_work';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Work|Works', $n);
	}

	public static function representingColumn() {
		return 'employer';
	}

	public function rules() {
		return array(
			array('employer, location, position', 'length', 'max'=>100),
			array('start_date, end_date', 'length', 'max'=>20),
			array('employer, location, position, start_date, end_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, employer, location, position, start_date, end_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'employer' => Yii::t('app', 'Employer'),
			'location' => Yii::t('app', 'Location'),
			'position' => Yii::t('app', 'Position'),
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('employer', $this->employer, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('position', $this->position, true);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}