<?php

/**
 * This is the model base class for the table "tbl_education".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Education".
 *
 * Columns in table "tbl_education" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $year
 * @property string $type
 * @property string $school
 * @property string $fb_info
 *
 */
abstract class BaseEducation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_education';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Education|Educations', $n);
	}

	public static function representingColumn() {
		return 'year';
	}

	public function rules() {
		return array(
			array('fb_info', 'required'),
			array('year, school, fb_info', 'length', 'max'=>20),
			array('type', 'length', 'max'=>100),
			array('year, type, school', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, year, type, school, fb_info', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'year' => Yii::t('app', 'Year'),
			'type' => Yii::t('app', 'Type'),
			'school' => Yii::t('app', 'School'),
			'fb_info' => Yii::t('app', 'Fb Info'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('year', $this->year, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('school', $this->school, true);
		$criteria->compare('fb_info', $this->fb_info, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}