<?php

/**
 * This is the model base class for the table "tbl_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "tbl_user" available as properties of the model,
 * followed by relations of table "tbl_user" available as properties of the model.
 *
 * @property string $id
 * @property string $fbid
 * @property string $createdAt
 * @property string $fb_info
 * @property string $code
 * @property double $mcl_louvain
 * @property double $mcl_oslom
 * @property double $louvain_oslom
 *
 * @property Clustering[] $clusterings
 * @property Friend[] $friends
 * @property Link[] $links
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('fbid', 'required'),
			array('mcl_louvain, mcl_oslom, louvain_oslom', 'numerical'),
			array('fbid, fb_info', 'length', 'max'=>20),
			array('code', 'length', 'max'=>50),
			array('createdAt', 'safe'),
			array('createdAt, fb_info, code, mcl_louvain, mcl_oslom, louvain_oslom', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, fbid, createdAt, fb_info, code, mcl_louvain, mcl_oslom, louvain_oslom', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clusterings' => array(self::HAS_MANY, 'Clustering', 'user'),
			'friends' => array(self::HAS_MANY, 'Friend', 'user'),
			'links' => array(self::HAS_MANY, 'Link', 'user'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'fbid' => Yii::t('app', 'Fbid'),
			'createdAt' => Yii::t('app', 'Created At'),
			'fb_info' => Yii::t('app', 'Fb Info'),
			'code' => Yii::t('app', 'Code'),
			'mcl_louvain' => Yii::t('app', 'Mcl Louvain'),
			'mcl_oslom' => Yii::t('app', 'Mcl Oslom'),
			'louvain_oslom' => Yii::t('app', 'Louvain Oslom'),
			'clusterings' => null,
			'friends' => null,
			'links' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('fbid', $this->fbid, true);
		$criteria->compare('createdAt', $this->createdAt, true);
		$criteria->compare('fb_info', $this->fb_info, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('mcl_louvain', $this->mcl_louvain);
		$criteria->compare('mcl_oslom', $this->mcl_oslom);
		$criteria->compare('louvain_oslom', $this->louvain_oslom);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}