<?php

/**
 * This is the model base class for the table "tbl_algorithm".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Algorithm".
 *
 * Columns in table "tbl_algorithm" available as properties of the model,
 * followed by relations of table "tbl_algorithm" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $description
 *
 * @property Clustering[] $clusterings
 */
abstract class BaseAlgorithm extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_algorithm';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Algorithm|Algorithms', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, description', 'required'),
			array('name', 'length', 'max'=>256),
			array('id, name, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clusterings' => array(self::HAS_MANY, 'Clustering', 'algorithm'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'clusterings' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}