<?php

/**
 * This is the model base class for the table "tbl_link".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Link".
 *
 * Columns in table "tbl_link" available as properties of the model,
 * followed by relations of table "tbl_link" available as properties of the model.
 *
 * @property string $ID
 * @property string $user
 * @property string $friend_1
 * @property string $friend_2
 *
 * @property User $user0
 */
abstract class BaseLink extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_link';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Link|Links', $n);
	}

	public static function representingColumn() {
		return 'ID';
	}

	public function rules() {
		return array(
			array('user, friend_1, friend_2', 'required'),
			array('user, friend_1, friend_2', 'length', 'max'=>20),
			array('ID, user, friend_1, friend_2', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user0' => array(self::BELONGS_TO, 'User', 'user'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'user' => null,
			'friend_1' => Yii::t('app', 'Friend 1'),
			'friend_2' => Yii::t('app', 'Friend 2'),
			'user0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID, true);
		$criteria->compare('user', $this->user);
		$criteria->compare('friend_1', $this->friend_1, true);
		$criteria->compare('friend_2', $this->friend_2, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}