<?php

/**
 * This is the model base class for the table "tbl_friend_cluster".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FriendCluster".
 *
 * Columns in table "tbl_friend_cluster" available as properties of the model,
 * followed by relations of table "tbl_friend_cluster" available as properties of the model.
 *
 * @property integer $id
 * @property string $friend
 * @property string $cluster
 * @property string $cor_cluster
 *
 * @property Friend $friend0
 * @property Cluster $cluster0
 * @property Cluster $corCluster
 */
abstract class BaseFriendCluster extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_friend_cluster';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FriendCluster|FriendClusters', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('friend, cluster, cor_cluster', 'length', 'max'=>20),
			array('friend, cluster, cor_cluster', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, friend, cluster, cor_cluster', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'friend0' => array(self::BELONGS_TO, 'Friend', 'friend'),
			'cluster0' => array(self::BELONGS_TO, 'Cluster', 'cluster'),
			'corCluster' => array(self::BELONGS_TO, 'Cluster', 'cor_cluster'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'friend' => null,
			'cluster' => null,
			'cor_cluster' => null,
			'friend0' => null,
			'cluster0' => null,
			'corCluster' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('friend', $this->friend);
		$criteria->compare('cluster', $this->cluster);
		$criteria->compare('cor_cluster', $this->cor_cluster);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}