<?php

/**
 * This is the model base class for the table "tbl_user_language".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserLanguage".
 *
 * Columns in table "tbl_user_language" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $fb_info
 * @property string $language
 *
 */
abstract class BaseUserLanguage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_user_language';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserLanguage|UserLanguages', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('fb_info, language', 'required'),
			array('fb_info, language', 'length', 'max'=>20),
			array('id, fb_info, language', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'fb_info' => Yii::t('app', 'Fb Info'),
			'language' => Yii::t('app', 'Language'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('fb_info', $this->fb_info, true);
		$criteria->compare('language', $this->language, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}