<?php

/**
 * This is the model base class for the table "tbl_friend".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Friend".
 *
 * Columns in table "tbl_friend" available as properties of the model,
 * followed by relations of table "tbl_friend" available as properties of the model.
 *
 * @property string $id
 * @property string $user
 * @property string $fbid
 * @property string $fb_info
 * @property string $name
 *
 * @property User $user0
 * @property FriendCluster[] $friendClusters
 * @property Link[] $links
 * @property Link[] $links1
 */
abstract class BaseFriend extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_friend';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Friend|Friends', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('user, fbid', 'required'),
			array('user, fbid, fb_info', 'length', 'max'=>20),
			array('name', 'length', 'max'=>50),
			array('fb_info, name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user, fbid, fb_info, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user0' => array(self::BELONGS_TO, 'User', 'user'),
			'friendClusters' => array(self::HAS_MANY, 'FriendCluster', 'friend'),
			'links' => array(self::HAS_MANY, 'Link', 'friend_1'),
			'links1' => array(self::HAS_MANY, 'Link', 'friend_2'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user' => null,
			'fbid' => Yii::t('app', 'Fbid'),
			'fb_info' => Yii::t('app', 'Fb Info'),
			'name' => Yii::t('app', 'Name'),
			'user0' => null,
			'friendClusters' => null,
			'links' => null,
			'links1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user', $this->user);
		$criteria->compare('fbid', $this->fbid, true);
		$criteria->compare('fb_info', $this->fb_info, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}