<?php

/**
 * This is the model base class for the table "tbl_cgroup".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cgroup".
 *
 * Columns in table "tbl_cgroup" available as properties of the model,
 * followed by relations of table "tbl_cgroup" available as properties of the model.
 *
 * @property string $id
 * @property string $user
 * @property string $clus_mcl
 * @property string $clus_louvain
 * @property string $clus_oslom
 *
 * @property User $user0
 * @property Cluster $clusMcl
 * @property Cluster $clusLouvain
 * @property Cluster $clusOslom
 */
abstract class BaseCgroup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_cgroup';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cgroup|Cgroups', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('user, clus_mcl, clus_louvain, clus_oslom', 'length', 'max'=>20),
			array('user, clus_mcl, clus_louvain, clus_oslom', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user, clus_mcl, clus_louvain, clus_oslom', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user0' => array(self::BELONGS_TO, 'User', 'user'),
			'clusMcl' => array(self::BELONGS_TO, 'Cluster', 'clus_mcl'),
			'clusLouvain' => array(self::BELONGS_TO, 'Cluster', 'clus_louvain'),
			'clusOslom' => array(self::BELONGS_TO, 'Cluster', 'clus_oslom'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user' => null,
			'clus_mcl' => null,
			'clus_louvain' => null,
			'clus_oslom' => null,
			'user0' => null,
			'clusMcl' => null,
			'clusLouvain' => null,
			'clusOslom' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user', $this->user);
		$criteria->compare('clus_mcl', $this->clus_mcl);
		$criteria->compare('clus_louvain', $this->clus_louvain);
		$criteria->compare('clus_oslom', $this->clus_oslom);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}