<?php

/**
 * This is the model base class for the table "tbl_events".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Events".
 *
 * Columns in table "tbl_events" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property string $start_time
 * @property string $end_time
 * @property string $location
 *
 */
abstract class BaseEvents extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_events';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Events|Events', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('id, name, start_time, end_time, location', 'required'),
			array('id', 'length', 'max'=>20),
			array('name, location', 'length', 'max'=>100),
			array('start_time, end_time', 'length', 'max'=>30),
			array('id, name, start_time, end_time, location', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'start_time' => Yii::t('app', 'Start Time'),
			'end_time' => Yii::t('app', 'End Time'),
			'location' => Yii::t('app', 'Location'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('start_time', $this->start_time, true);
		$criteria->compare('end_time', $this->end_time, true);
		$criteria->compare('location', $this->location, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}